### PR TITLE
Handle verifyIdToken failing due to an expired token

### PR DESCRIPTION
**Pull request by Francesco-Lanciana**
This happens when the firebase token has expired and you attempt to call withAuthUserTokenSSR. This in turn calls verifyIdToken which will throw an error if the key ID of the firebase token has expired.

I believe issue #114 is caused as a result of this issue.

Let me know if there is anything else I need to add. This bug is causing some me some grief so I'm happy to work on refine this ASAP if need be.

### CODE REVIEW

**Comment by kmjennison** [comment]
Thanks for this PR!

I'm not sure if catching all errors is the best approach. The `verifyIdToken` function [already handles the `auth/id-token-expired` error](https://github.com/gladly-team/next-firebase-auth/blob/main/src/firebaseAdmin.js#L63). This package should throw other Firebase errors that it's not handling so the developer can handle them.

Are there specific [Firebase admin error codes](https://firebase.google.com/docs/auth/admin/errors) that this package should handle?

The philosophy of `next-firebase-auth` is to use the client-side Firebase JS SDK as the source of truth—so if the server-side auth fails, maybe it makes sense to provide an unauthenticated user and let the client side auth load and update cookies as needed. However, if the Firebase error is permanent (e.g., there's some configuration error), then SSR auth would be broken indefinitely with no warning to the developer.

**Comment by Francesco-Lanciana** [comment]
Oh interesting, I didn't realise you had wrapped firebase's verifyIdToken in another function. I think that makes sense, and it definitely makes it easier to reason about by treating the client as the source of truth. So in that case would you just recommend adding another if statement in the catch that handles this specific error, and if encountered returns an empty object?
```
// If the user's ID token has expired, refresh it if possible.
if (refreshToken && e.code === FIREBASE_ERROR_TOKEN_EXPIRED) {
  newToken = await refreshExpiredIdToken(refreshToken)
  firebaseUser = await admin.auth().verifyIdToken(newToken)
} else if (e.code === "auth/argument-error") {
  return {};
} else {
  // Otherwise, throw.
  throw e
}
```

"auth/argument-error" is the error code generated by the firebase error (refer to image below)

image

image


I also did some more digging into firebase-admin and this kid claim error. It seems firebase-admin will at semi-random intervals pull down the [certs from google](https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com) and then compare the JWT token given to verifyIdToken. Google wants the kid header claim in our token to correspond to one of the public keys in this certs ([Link](https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library)).

It seems like everyone should be encountering this error if they go to a page that makes use of `withAuthUserTokenSSR` after they have been inactive for some period of time, so I'm a little confused as to why there has only been one issue regarding this problem. Have you ever encountered it?

**Comment by kmjennison** [comment]
That's really helpful info, thanks. Just curious, did you find any info on how frequently those certificates are rotated?

> would you just recommend adding another if statement in the catch that handles this specific error, and if encountered returns an empty object

Yes, this sounds good. Do you know if refreshing the ID token will also successfully handle the `kid` problem thrown with `auth/argument-error`? If so we could refresh and provide the user instead of just setting the user to unauthed.

Not sure if you had a reason to close this issue, but feel free to reopen.

**Comment by Francesco-Lanciana** [comment]
I did have a look at that, I haven't managed to find how often they are rotated but Googles recommendation is to refresh the certs every X hours where X is specified by the max-age part of the Cache-Control header of the returned cert response ([Link to code](https://github.com/firebase/firebase-admin-node/blob/d961c3f705a8259762a796ac4f4d6a6dd0992eb1/src/utils/jwt.ts#L99)). You can go to [this link](https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com) to get the certs. The max-age seems to be anywhere between 5-6 hours. I think Google actually rotates them roughly every few days because that's how long I needed to be inactive for the bug to occur.

From running tests with the code I had submitted it seemed to fix the problem, but I wasn't entirely sure if there would be unintended side effects. I'm guessing there would have been since I was catching all errors and not just auth/argument-error. If we only refresh for this specific error I don't see why it wouldn't work though. 

Just to double check, by refreshing did you mean using `createAuthUser`?

Oh yep I didn't mean to close it, it's just that I accidentally did this work on the main branch and had to move it over to another branch which caused this issue to be auto-closed. I'll create another PR with this new approach shortly :)

**Comment by kmjennison** [comment]
By refreshing, I actually mean using the refresh token to get a new ID token like we do [here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/firebaseAdmin.js#L64)—so we'd do this for both `auth/id-token-expired` and `auth/argument-error`. I'm assuming that would fix the expired `kid` (?), but I'm not sure.

An aside, but somewhat related: there might be other [error codes](https://firebase.google.com/docs/reference/node/firebase.auth.Error) that would make sense to handle by creating an unauthed AuthUser, such as `auth/invalid-user-token` and `auth/user-token-expired`.

**Comment by Francesco-Lanciana** [comment]
@kmjennison Sorry for the delay, been flat out the last few days. As for refreshing the token, that seems like it would do the trick!

Yeah I agree, `auth/user-disabled` should probably also should probably also return an unauthed AuthUser. 

Out of curiosity, what happens when you refresh the token on the server? Is that propogated back to the client or is it just used for this server interaction, and then the client would also need to refresh the token? From what I can see the only time the cookies are set (including the idToken) is when you call the login endpoint, so I'm a little confused as to what happens when the ID token we get from our initial login expires (i.e. we have been on the site for 1 hour). Wouldn't every new page reload after that use an outdated ID token so our server would be refreshing it every time?

**Comment by kmjennison** [comment]
@Francesco-Lanciana No worries!

> when the ID token we get from our initial login expires (i.e. we have been on the site for 1 hour). Wouldn't every new page reload after that use an outdated ID token so our server would be refreshing it every time?

Your description is partially correct. If the user is _active_ on the site for >1 hour, the client JS SDK will refresh the ID token, which will update the cookies with a new ID token. Any server renders soon after that use [`withAuthUserTokenSSR`](https://github.com/gladly-team/next-firebase-auth#withauthusertokenssr-options-getserversidepropsfunc---authuser---) will have a valid ID token and won't require a token refresh.

If the user leaves the site for more than an hour, the ID token in the cookies will expire, and the next server render using `withAuthUserTokenSSR` _will_ require a token refresh.

If the backend does not need an ID token, you can use [`withAuthUserSSR`](https://github.com/gladly-team/next-firebase-auth#withauthuserssr-options-getserversidepropsfunc---authuser---), which won't do any token refreshes.

**Comment by kmjennison** [comment]
Opened this issue: #174

**Pull request closed without merging**
