### PR TITLE
feat(firebaseAdmin): fix to pass user custom user claims to createCustomToken

### PR DESCRIPTION
**Pull request by velddev**
Continuation of @takashi's PR #495.

Added the tests to get this PR over the line.

### CODE REVIEW

**Review by kmjennison — CHANGES_REQUESTED** [review]
Thanks for opening this PR! Appreciate it.

Could you make this PR against the `v1.x` branch? That's where most active development is happening in prep for the v1 release. It will take some edits due to the updates to Firebase.

**Comment by velddev** [comment]
hey @kmjennison it was easier to reimplement the same code on the other branch, couldn't really merge main and v1.x with changes on the branch well. Apologies for the noise.

--> #659

**Comment by kmjennison** [comment]
@velddev No worries at all! But heads up, it looks like you closed #659 (not sure if intentional).

**Comment by velddev** [comment]
@kmjennison long story short -- working through takashi's fork made it really hard for me to sync changes from the main repo. I'll reopen a PR in a second. 😅

**Pull request closed without merging**
