### PR TITLE
Let user specify the firebase app name

### PR DESCRIPTION
**Pull request by justinmann**
Safari / Firebase do not like each other: https://github.com/firebase/firebase-js-sdk/issues/7888

To workaround their animosity, we need to change the app name for firebase to something without [].

### CODE REVIEW

**Review by kmjennison — CHANGES_REQUESTED** [review]
Thanks, this is great! Only change: could you get the linting to pass? Looks like there's a dependency cycle.

**Comment by MvRemmerden** [comment]
@justinmann If you don't plan on moving this forward, I could give it a try, as I think this might also help with the problems we are seeing that are blocking users from upgrading above `9.16.0` (e.g. https://github.com/gladly-team/next-firebase-auth/issues/711 and https://github.com/gladly-team/next-firebase-auth/issues/710).

@kmjennison Do you have any preference how to solve the dependency problem? There are a couple of ways this could be tackled, and I want to make sure it's going the direction you prefer.

**Comment by MvRemmerden** [comment]
I gave it a try in https://github.com/gladly-team/next-firebase-auth/pull/716.

**Comment by kmjennison** [comment]
@MvRemmerden Thanks! Commented on that PR.

**Comment by kmjennison** [comment]
Closed in #716.

**Pull request closed without merging**
