### PR TITLE
Support modular Firebase 9

### PR DESCRIPTION
**Pull request by HofmannZ**
This PR adds support for Firebase 9. It does not change the API of `next-firebase-auth`, so the refactor for users of the package will be relatively simple.

This PR also updates the mocks, tests, and examples accordingly.

### CODE REVIEW

**Comment by gavinharris-dev** [comment]
Looks great! Just wondering should we also update the Readme (https://github.com/gladly-team/next-firebase-auth#using-the-firebase-apps)? You've already covered all the Examples which is great!

Although this is not really a breaking change for `next-firebase-api` it probably will be for existing applications as they will need to update to Firebase 9.0.0 right? - Does this change necessitate an few pointers to upgrading from Firebase v8? Even perhaps a link out to the Firebase official docs?

**Comment by HofmannZ** [comment]
@gavinharris-dev - Thanks for the feedback! I totally missed that readme section.

I think linking to the official docs would be great, this official article covers the upgrade: https://firebase.google.com/docs/web/modular-upgrade. I will also add a small example in the readme directly for ease of use.

**Comment by dukesx** [comment]
Any ETA on this ? At least Firebase UI is almost done migrating to Firebase 9. Its not official but the @next version seems to work pretty well. This package is now the only one waiting over a PR, that has already almost done everything for them. I wonder what's the wait. @HofmannZ  Excellent Work and Kudos to you !

**Comment by HofmannZ** [comment]
@dukesx - I'm done as far as this PR is concerned. I also saw that the Gladly team is setting up pipelines for v1 of the `next-forename-auth` package 📦.

So, I assume this PR will soon be included in a prerelease of v1 🚀.

**Review by kmjennison — CHANGES_REQUESTED** [review]
@HofmannZ Thanks for the thorough PR. Looks great. Only one change: could you resolve the merge conflicts in the README?

**Comment by kmjennison** [comment]
@dukesx What version of firebaseui-web are you using that works well? [This PR](https://github.com/firebase/firebaseui-web/pull/850) suggests a stable version with v9 support is a long way off, so maybe we can use an unstable release just to get the example app working..

**Comment by HofmannZ** [comment]
@kmjennison - Rebased against the `v1.x` branch. should be ready to go.

**Comment by HofmannZ** [comment]
@kmjennison - It's this going to be included in a canary build? 🔜

**Comment by kmjennison** [comment]
@HofmannZ Yes, just released. Thanks!

**Pull request merged**
